FROM opensuse/leap:15.6

COPY preclone_zypper_dep.sh /tmp/preclone_zypper_dep.sh

RUN /tmp/preclone_zypper_dep.sh

WORKDIR /work
RUN git clone https://github.com/os-autoinst/os-autoinst-distri-opensuse

COPY preprepare_zypper_common.sh /tmp/preprepare_zypper_common.sh
RUN /tmp/preprepare_zypper_common.sh

# perl module Inline::Python needs Python.h
RUN zypper in -y python3-devel

WORKDIR /work/os-autoinst-distri-opensuse
RUN make prepare

COPY postprepare_zypper_common.sh /tmp/postprepare_zypper_common.sh
RUN /tmp/postprepare_zypper_common.sh

# patch this script to avoid trouble in running podman within podman
RUN echo "podman -v" > tools/test_isotovideo

RUN make test-yaml-valid && make tidy-check
RUN time make test-compile
RUN make unit-test || time PERL5OPT=-MCarp::Always prove --time --verbose -l -Ios-autoinst/ t/
RUN make test
