FROM opensuse/leap:15.5

COPY preclone_zypper_dep.sh preprepare_zypper_common.sh postprepare_zypper_common.sh /tmp/

RUN chmod +x /tmp/preclone_zypper_dep.sh && /tmp/preclone_zypper_dep.sh

WORKDIR /work
RUN git clone https://github.com/os-autoinst/os-autoinst-distri-opensuse

RUN chmod +x /tmp/preprepare_zypper_common.sh && /tmp/preprepare_zypper_common.sh

# perl module Inline::Python needs Python.h
RUN zypper in -y python3-devel

WORKDIR /work/os-autoinst-distri-opensuse
RUN make prepare

RUN chmod +x /tmp/postprepare_zypper_common.sh && /tmp/postprepare_zypper_common.sh

# patch this script to avoid trouble in running podman within podman
RUN echo "podman -v" > tools/test_isotovideo

#RUN make test-yaml-valid && make tidy-check
#RUN time make test-compile
#RUN make unit-test || time PERL5OPT=-MCarp::Always prove --time --verbose -l -Ios-autoinst/ t/
#RUN make test