FROM opensuse/leap:15.5

# get an updated system
RUN zypper ref && zypper up -y 

# git is needed to get the code
RUN zypper in -y git

WORKDIR /work
RUN git clone https://github.com/os-autoinst/os-autoinst-distri-opensuse

# install what requested in https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/9a8b06f39afe23b1a367453f2d5c4ed676815c1a/CONTRIBUTING.md?plain=1#L35
RUN zypper in -y os-autoinst-distri-opensuse-deps

# make needed to run `make prepare` but not provided by any packages till now
RUN zypper in -y make

# Python needed by https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/9a8b06f39afe23b1a367453f2d5c4ed676815c1a/tools/wheel#L1C3-L1C19
RUN zypper in -y python3 python3-PyYAML

# make prepare needs cpanm
RUN zypper in -y perl-App-cpanminus

# cpanm needs gcc
RUN zypper in -y gcc

# perl module Inline::Python needs Python.h
RUN zypper in -y python3-devel

# perl module Net::SSH2 needs ssh2
RUN zypper in -y libssh2-devel

# perl module Net::DBus needs DBUS>=1.3
RUN zypper in -y libdbus-c++-devel

WORKDIR /work/os-autoinst-distri-opensuse
RUN make prepare

# Still some dependency are missing, even if make prepare is sucesfully over

# Dependency needed by test-yaml-valid. This one is mentined https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/9a8b06f39afe23b1a367453f2d5c4ed676815c1a/CONTRIBUTING.md?plain=1#L48
RUN zypper in -y python3-yamllint

# Dependency needed by make target test-compile. This one is mentioned here https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/9a8b06f39afe23b1a367453f2d5c4ed676815c1a/CONTRIBUTING.md?plain=1#L35C64-L35C76
RUN zypper in -y gnu_parallel

# dependency needed by make target 'tidy-check'
RUN zypper in -y perl-Code-TidyAll

# dependency needed by make target 'test-isotovideo'
RUN zypper in -y podman
# patch this script to avoid trouble in running podman within podman
RUN echo "podman -v" > tools/test_isotovideo

RUN make test
