name: Check OSADO dependency by build images

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_leap_15sp5:
    # No matter which image, as soon as it can provide podman
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Preconfigure
        run: apt install podman

      - name: Build image
        run: |
          podman --version
          ls -lai
